name: Update Phishing Email Blacklist

on:
  schedule:
    - cron: '0 */4 * * *'  # Run every 4 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-blacklist:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install slack-sdk PureCloudPlatformClientV2 email-validator tenacity
        
    - name: Run blacklist update script
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        GENESYS_CLIENT_ID: ${{ secrets.GENESYS_CLIENT_ID }}
        GENESYS_CLIENT_SECRET: ${{ secrets.GENESYS_CLIENT_SECRET }}
        GENESYS_REGION: ${{ secrets.GENESYS_REGION }}
        GENESYS_DATA_TABLE_ID: ${{ secrets.GENESYS_DATA_TABLE_ID }}
      run: python update_blacklist.py
      
    - name: Upload timestamp file
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: last-run-timestamp
        path: last_run_timestamp.txt
        retention-days: 1
        
    - name: Download previous timestamp
      uses: actions/download-artifact@v3
      with:
        name: last-run-timestamp
        path: ./
